---
version: "2"

run:
  timeout: 3m

linters:
  default: all
  disable:
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - depguard # not relevant (dependency management)
    - cyclop # duplicate of gocyclo
    - bodyclose # too many false positives: https://github.com/timakin/bodyclose/issues/30
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - lll
    - nlreturn
    - noctx
    - paralleltest
    - revive
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocyclo:
      min-complexity: 12
    goconst:
      min-len: 5
      min-occurrences: 4
    misspell:
      locale: US
    funlen:
      lines: -1
      statements: 50
    godox:
      keywords:
        - FIXME
  exclusions:
    rules:
      - path: (.+)_test.go
        linters:
          - cyclop
          - funlen
          - gocognit
          - goconst
          - gocyclo
          - godot
          - maintidx

issues:
  max-same-issues: 0
