displayName: Traefik Template Plugin
type: middleware
iconPath: .assets/icon.png

import: github.com/xabinapal/traefik-template-plugin

summary: 'Template plugin that injects headers into requests forwarded to upstream services.'

testData:
  headers:
    X-Demo: test
    X-URL: '{{URL}}'
