---
name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: A clear description of what the bug is and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Configure the plugin with...
        2. Send a request to...
        3. See error...
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: input
    id: traefik-version
    attributes:
      label: Traefik version
      placeholder: "v3.0.0"
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Your plugin configuration (remove sensitive data)
      placeholder: |
        ```yaml
        http:
          middlewares:
            template:
              plugin:
                template:
                  headers:
                    X-Demo: test
                    X-Url: http://localhost
        ```
      render: yaml
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (remove sensitive data)
      placeholder: |
        ```
        Paste relevant logs here...
        ```
      render: text
