---
name: unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GOPATH: ${{ github.workspace }}/go
  REPOPATH: ${{ github.workspace }}/go//src/github.com/${{ github.repository }}

jobs:
  go:
    name: go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.21
          - 1.22
    env:
      GOLANGCI_LINT_VERSION: v2.1.6
    defaults:
      run:
        working-directory: ${{ env.REPOPATH }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPOPATH }}
          fetch-depth: 0

      - name: install go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ env.REPOPATH }}

      - name: run tests
        run: go test -v -cover ./...

  yaegi:
    name: yaegi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        yaegi-version:
          - v0.15.0
          - v0.16.1
    defaults:
      run:
        working-directory: ${{ env.REPOPATH }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPOPATH }}
          fetch-depth: 0

      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
          cache: false

      - name: install yaegi ${{ matrix.yaegi-version }}
        run: |
          curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b /usr/local/bin ${{ matrix.yaegi-version }}

      - name: run tests
        run: |
          for pkg in $(go list ./...); do
            yaegi test -v "${pkg}"
          done